FROM amazon/aws-lambda-python:3.12

# Install wget, unzip, and Chrome dependencies
RUN microdnf install -y wget unzip

# Copy and run the chrome installer script
COPY ./chrome-installer.sh /chrome-installer.sh
RUN chmod +x /chrome-installer.sh
RUN /chrome-installer.sh

# Install Python dependencies
COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

# Copy the main application code
COPY main.py ./

# Set the Lambda handler
CMD ["main.lambda_handler"]
